name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: build using npm
        run: |
          ls -la
          pwd
          npm install
          ls -la
          cd /usr
          ls -la
          cd /usr/local/share
          ls -la
